Algoritmo Ejercicio5
	//(X,Y1)=Coordenadas
	escribir "INGRESE PUNTO X"
	LEER X
	ESCRIBIR "INGRESE PUNTO Y"
	LEER Y1
	Si (X^2)+Y1^2=25 Entonces
		ESCRIBIR "LAS COORDENADAS SI SE ENCUENTRAN EN EL CÍRCULO"
	SiNo
		ESCRIBIR "LAS COORDENADAS NO SE ENCUENTRAN EN EL CÍRCULO"
	Fin Si
FinAlgoritmo
